<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="46" started-at="2019-09-02T18:35:29Z" finished-at="2019-09-02T18:35:29Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="46" started-at="2019-09-02T18:35:29Z" finished-at="2019-09-02T18:35:29Z">
      <class name="test.maven.selenium.PracticeTest">
        <test-method status="FAIL" signature="testPracticeMethod1()[pri:0, instance:test.maven.selenium.PracticeTest@66a3ffec]" name="testPracticeMethod1" duration-ms="10" started-at="2019-09-02T18:35:29Z" finished-at="2019-09-02T18:35:29Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:55)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertFalse(Assert.java:39)
at junit.framework.Assert.assertFalse(Assert.java:47)
at test.maven.selenium.PracticeTest.testPracticeMethod1(PracticeTest.java:11)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPracticeMethod1 -->
        <test-method status="PASS" signature="testPracticeMethod2()[pri:0, instance:test.maven.selenium.PracticeTest@66a3ffec]" name="testPracticeMethod2" duration-ms="6" started-at="2019-09-02T18:35:29Z" finished-at="2019-09-02T18:35:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPracticeMethod2 -->
      </class> <!-- test.maven.selenium.PracticeTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
